### ISSUE TITLE
Running with Darpa E3 dataset

### ISSUE THREAD

**Issue by rimon15** [jun-zeng/ShadeWatcher#2]
Hello,

I ran the parser with the following arguments in order to store all of the KGs and entities for the TRACE dataset: ./driverdar -dataset e3_trace -trace [directory of all TRACE json files] -multithread 36 -sf -se

This produced the edgefact_tmp files, procfact, filefact, socketfact, and nodefact files. Most of the edgefact_tmp files are empty as you can see below. It seems only the edgefact_tmp 0-12 are non-empty. I am not sure which edgefact files are supposed to be used as the actual edgelist.
![image](https://user-images.githubusercontent.com/13021996/196421392-7231994e-8872-49f7-86d2-b82e2f2eda60.png)

After looking in the code, I see that the edgefact file should contain the edge, node hashes, relation (not sure what that is?), sequence, session (not sure what that is?), and timestamp. 

I also see what the proc, file, socket are storing. Is nodefact storing all of the node IDs?

Overall, I am not sure to go from these files to running the recommender. I also looked at the https://github.com/jun-zeng/ShadeWatcher/tree/main/data/encoding readme but I'm still not sure.

If you could explain how you ran the train/test for the recommender from the parsed files, that would be great.

Thanks,
Rimon

**Comment by jun-zeng** [comment]
Hi, 

Each edgefact_tmp_x file stores KG edges parsed from the corresponding DARPA log file (e.g., edgefact_tmp_1 from ta1-trace-e3-official-1.json). The last edgefact_x file stores KG edges and the total number of edges in all the parsed DARPA log files. 

Some edgefact_tmp_x files may be empty because our "noise" reduction algorithms have filtered out all the constituent KG edges.

The relation in an edgefact_tmp_x file denotes system calls (see https://github.com/jun-zeng/ShadeWatcher/blob/main/data/encoding/test/relation2id.txt for details) used in logs. The session indicates the active user session that requests system calls. For example, whenever you log in to a server using SSH, you create a new session with a unique session ID.

Yes, nodefact stores the IDs of all the KG nodes, including files, processes, and network sockets.

To train a recommendation model, you need to extract system entity interactions from a KG to construct training samples (e.g., benign system interactions).

A toy example of running our model can be found at https://github.com/jun-zeng/ShadeWatcher/blob/main/docs/recommending.md.

**Comment by rimon15** [comment]
Thank you for the explanation.
