### ISSUE TITLE
 One Hash_ID corresponds to multiple Socket?How to divide the Darpa Dataset into benigh and attack？

### ISSUE THREAD

**Issue by yemai666** [jun-zeng/ShadeWatcher#7]
Hi，
After running the parser in the DARPA-THEIA dataset，I found some problems：
1）i used the commend -sf,so i get 5 files:file/proc/socket/node/edge fact,but i found that in socketfact,there are a number of different Hash_id values corresponding to the same socket,Is this correct?like this：
<img width="429" alt="image" src="https://user-images.githubusercontent.com/48974017/210190742-98f2d976-65d6-4117-8b6b-122ddfaea571.png">

2）Also in filefct，The same Hash_id also exists for different File data，like this：
Hash_ID 5509527765767947792 correspond to run/shm/org.chromium.uqWgpy  and  /run/shm/org.chromium.An7oCE

3）I converted the timestamp information in the generated Edge into time, hoping to give marks according to the information in the GroundTruth file, but I did not find the corresponding data. For example, In 20180410 1400 THEIA -- Firefox Backdoor w/ Drakon in-memory attack: The attack was supposed to happen at 13:41, but ended at 6:14 on April 10, 2018 in the Edge file：

/usr/bin/python,getpeername,128.55.12.10:53,18,0,"2018-04-10 06:14:44,419790"
/usr/bin/python,mkdir,128.55.12.10:53,19,0,"2018-04-10 06:14:44,419798"
128.55.12.10:53,send,/usr/bin/python,25,0,"2018-04-10 06:14:51,468079"
/var/lib/postgresql/9.1/main/pg_stat_tmp/pgstat.stat,write,postgres:,2,0,"2018-04-11 00:44:33,449617"
postgres:,mkdir,127.0.0.1:33455,4,0,"2018-04-11 00:44:33,449671"
127.0.0.1:33455,send,postgres:,0,0,"2018-04-11 00:44:33,449764"

**May I ask whether this piece of information is missing in Edge, or there is something wrong with the way I search? I have not found other attack information mentioned in GroundTruth. May I ask how you marked the attacks in Edge according to GroundTruh? Is it based on the Event Log in GroundTruth or what?**

**Comment by jun-zeng** [comment]
Hi Mai, hopefully, I have answered your questions in your previous email:

Hi Mai,

Thanks for the questions.

Q1: You are correct. While parsing the DARPA dataset, we directly use the UUID given in the dataset as the hash ids of system entities. I suppose the sockets, even with the same IP address, are provided different UUIDs because they have different network ports.

Q2: Again, you are correct. We directly use UUID in the DARPA dataset as our hash ids. Honestly, I did not know how DAPRA generates UUIDs for system entities. I assume that it is reasonable. In our experiment, we find that two files with different names may share the same hash id due to the hash collision problem. We have tried to avoid the problem by using a long hash id.

Q3: To label the ground truth, I first locate the malicious behaviors in the dataset (Table VI in Watson [NDSS’2021]) and manually identify the potentially malicious system entity interactions according to the public DARPA document (https://drive.google.com/drive/folders/1ATro9_PaoNlg376yA_moI1MbJGF-_HaV).

Thanks,
Jun
